services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:4000"
    environment:
      - PORT=4000
      - NATS_SERVERS=nats://nats-server:4222

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: dockerfile.prod
    image: ms-auth-prod
    ports:
      - ${MS_AUTH_PORT}:${MS_AUTH_PORT}
    environment:
      - PORT=${MS_AUTH_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  ms-products:
    build:
      context: ./ms-products
      dockerfile: dockerfile.prod
    image: ms-products-prod
    environment:
      - PORT=4001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  ms-orders:
    build:
      context: ./ms-orders
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: ms-orders-prod
    environment:
      - PORT=4002
      - DATABASE_URL=${DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  ms-payments:
    build:
      context: ./ms-payments
      dockerfile: dockerfile.prod
    ports:
      - ${MS_PAYMENTS_PORT}:${MS_PAYMENTS_PORT}
    environment:
      - PORT=${MS_PAYMENTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
